### ISSUE TITLE
Does pump2status.net work for posting notes or not yet?

### ISSUE THREAD

**Issue by larjona** [e14n/pump2status#6]
Hello
Congratulations for your work.
I've have used pump2status.net to connect my identi.ca account (larjona@identi.ca) to my quitter.se account (larjona@quitter.se). 
In settings, I have enabled "Post pump network activities to my StatusNet site".
I have posted a note to "Public" ( https://identi.ca/larjona/note/sBAcrfm9Qg-_41y-2H9WUQ ) but it does not show up in my quitter.se timeline ( https://quitter.se/larjona ). No error messages, nothing happened. I've seen my note in the ofirehose.

Is this feature already working or it's still in development?

Thank you very much.

**Comment by mrvdb** [comment]
FYI, i have it working locally, so the functionality is definitely there.

**Comment by larjona** [comment]
I see it's working for others, so I'll close this bug and try to solve/diagnose my particular issues. Thanks everybody.
